### ISSUE TITLE
CHAPTER 1 도메인 모델 시작

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#1]
질문을 남겨주세요!

**Comment by ksy90101** [comment]
p20. 엔티티의 식별자 생성 부분에서 여러가지 방법으로 식별자를 만들 수 있는데, 각자 어떤 상황에서 사용할 수 있을까요?

**Comment by ksy90101** [comment]
p34. 최근의 개발 프레임워크나 개발 도구는 set 메서그다 아닌 private 필드에 직접 값을 할당할 수 있는 기능을 제공한다고 하는데, 혹시 아시는게 있을까요?

**Comment by ksy90101** [comment]
https://stackoverflow.com/questions/10739914/what-is-the-difference-between-3-tier-architecture-and-a-mvc

**Comment by KS-KIM** [comment]
https://youtu.be/dXRX-RT2lVg

**Comment by aegis1920** [comment]
https://helloworld.kurly.com/blog/jpa-uuid-sapjil/

**Comment by ksy90101** [comment]
https://brunch.co.kr/@cg4jins

**Comment by ksy90101** [comment]
https://medium.com/myrealtrip-product/what-is-domain-driven-design-f6fd54051590?source=collection_home---4------18-----------------------

**Comment by ksy90101** [comment]
https://medium.com/myrealtrip-product/what-is-domain-driven-design-f6fd54051590

**Comment by KS-KIM** [comment]
https://martinfowler.com/bliki/ValueObject.html

**Comment by aegis1920** [comment]
> p34. 최근의 개발 프레임워크나 개발 도구는 set 메서그다 아닌 private 필드에 직접 값을 할당할 수 있는 기능을 제공한다고 하는데, 혹시 아시는게 있을까요?

MyBatis의 경우, private 필드에 직접 값을 할당할 수 있습니다. MyBatis에서 직접 값을 할당하는 과정입니다.

1. MyBatis는 객체를 결과로 받거나 파라미터로 받을 때  DTO 바인딩을 이용할 수 있는데 이때 Reflector 클래스의 도움을 받습니다.
2. Reflector 클래스의 생성자를 보면 Getter, Setter를 직접 찾아서 메서드 명을 확인하고 추가하는 부분을 볼 수 있습니다. ([링크](https://github.com/mybatis/mybatis-3/blob/b791f4476f6fba6d717196d0489820eb65a946bb/src/main/java/org/apache/ibatis/reflection/Reflector.java#L67-L68))
3. addSetField() 부분을 보시면 SetFieldInvocker 라고하는 클래스([링크](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/reflection/invoker/SetFieldInvoker.java))가 Set을 위해 사용되는데 일단 set 함수를 먼저 실행해보고 IllegalAccessException 이 일어나면 catch 문에서 접근제한자를 변경해 set하게 되는 구조입니다.
4. 즉, setter를 작성하지 않았을 때 직접 접근제한자를 변경해서 직접 값을 할당하게 됩니다.
