### ISSUE TITLE
CHAPTER 11 CQRS

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#11]
질문을 남겨주세요!

**Comment by KS-KIM** [comment]
데이터 일관성 보장

[316p 내용 참고 링크](https://docs.microsoft.com/ko-kr/previous-versions/msp-n-p/dn589800(v=pandp.10))

**Comment by KS-KIM** [comment]
https://www.baeldung.com/spring-boot-caffeine-cache

**Comment by KS-KIM** [comment]
https://www.popit.kr/cqrs-eventsourcing/

**Comment by KS-KIM** [comment]
# 참고 링크

- https://www.youtube.com/watch?v=xf0kXMTFJm8&list=PLwouWTPuIjUgr29uSrSkVo8PRmem6HRDE&index=5
- https://www.youtube.com/watch?v=H1IF3BUeFb8&list=PLwouWTPuIjUgr29uSrSkVo8PRmem6HRDE&index=5
- https://radekmaziarka.pl/2018/01/08/cqrs-third-step-simple-read-model/
- https://brunch.co.kr/@springboot/423
