### ISSUE TITLE
CHAPTER 2 SQL 튜닝 용어를 직관적으로 이해하기

### ISSUE THREAD

**Issue by ksy90101** [Woohan-TDD/ddd-start#18]

**Comment by ksy90101** [comment]
p52에서 
> 여러 개의 테이블을 JOIN해서 활용할 때는 성능을 고려한 최적화된 뷰를 생성함으로써 일관된 성능을 제공할 수 있습니다.
이말이 뭔말일까요,,?

**Comment by KS-KIM** [comment]
57p 상관 서브쿼리 예시가 잘못된 것 같습니다. 조건절이 일부 누락된 것 같네요.

**Comment by KS-KIM** [comment]
> 여러 개의 테이블을 JOIN해서 활용할 때는 성능을 고려한 최적화된 뷰를 생성함으로써 일관된 성능을 제공할 수 있습니다.

JOIN하여 결과를 얻어야 하는 경우가 잦을 때, 미리 성능 최적화를 고려하여 JOIN을 맺은 뷰를 만들어두고 이를 사용하면 매번 JOIN 쿼리를 작성하지 않으면서 최적화된 조회 쿼리를 작성할 수 있으므로 일관된 성능을 제공할 수 있다는 말 같습니다.

**Comment by KS-KIM** [comment]
단일행 서브쿼리는 서브쿼리 결과가 1건의 행으로 반환되니 비상관 서브쿼리라고 볼 수 있을까요?

**Comment by KS-KIM** [comment]
mysql b-tree 인덱스 키 추가 및 삭제 -> realmysql 211p 참조

**Comment by KS-KIM** [comment]
lateral join
- https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html

**Comment by KS-KIM** [comment]
문자열에 인덱스 적용하기 (아래 사례는 postgresql이지만 )
- https://jojoldu.tistory.com/590

**Comment by KS-KIM** [comment]
b-tree, b+tree 시뮬레이션 해보기
- https://www.cs.usfca.edu/~galles/visualization/BTree.html
- https://www.cs.usfca.edu/~galles/visualization/BPlusTree.html

**Comment by KS-KIM** [comment]
where절 조건 순서에 따라 엑세스 조건이 달라지는지 찾아보기

**Comment by KS-KIM** [comment]
mysql 이외의 DB에서도 필터 조건같은걸 고려해야 하는가? (82p)

**Comment by ksy90101** [comment]
https://jojoldu.tistory.com/481

**Comment by ksy90101** [comment]
https://weicomes.tistory.com/191

**Comment by KS-KIM** [comment]
https://jojoldu.tistory.com/596

**Comment by KS-KIM** [comment]
> mintjordy
> 이모지 정렬기준을 지원안하는 콜레이션 utf8_bin 인 테이블과 조인했다가  에러난적 있었습니당
> collation 'utf8_general_ci' is not valid for character set 'utf8mb4'

**Comment by KS-KIM** [comment]
> where절 조건 순서에 따라 엑세스 조건이 달라지는지 찾아보기

https://stackoverflow.com/questions/4035760/does-the-order-of-fields-in-a-where-clause-affect-performance-in-mysql/4035997

위 내용에 따르면 순서에 영향을 받지 않는 것 같습니다.
