### ISSUE TITLE
CHAPTER 3 SQL 튜닝의 실행 계획 파헤치기

### ISSUE THREAD

**Issue by ksy90101** [Woohan-TDD/ddd-start#19]

**Comment by KS-KIM** [comment]
환경설정 귀찮으시면 [여기](https://github.com/Woohan-TDD/book-study/tree/main/%EC%97%85%EB%AC%B4%EC%97%90%20%EB%B0%94%EB%A1%9C%20%EC%93%B0%EB%8A%94%20SQL%20%ED%8A%9C%EB%8B%9D/3%EC%9E%A5/ks_kim) 참고하셔서 도커로 설치하면 됩니다. 볼륨 지정은 안해놨으니 필요하면 docker-compose 파일 수정하시면 됩니다.

**Comment by ksy90101** [comment]
p125~126 실행계획이 책과 다르게 나오는데, 저만 그런가유?
```sql
EXPLAIN
SELECT 사원.사원번호, 사원.이름, 사원.성,
       (SELECT MAX(부서번호)
           FROM 부서사원_매핑 AS 매핑 WHERE 매핑.사원번호 = 사원.사원번호) AS 카운트
FROM 사원
WHERE 사원.사원번호 = 100001;
```

**Comment by ksy90101** [comment]
p127 실행계획이 책과 다르게 나오는데, 저만 그런가유?
```sql
EXPLAIN
SELECT (SELECT COUNT(*)
        FROM 부서사원_매핑 AS 매핑) AS 카운트,
       (SELECT MAX(연봉)
        FROM 급여)            AS 급여;
```

**Comment by ksy90101** [comment]
p128 쿼리가 안된다면
https://info-lab.tistory.com/274

**Comment by KS-KIM** [comment]
144 key_len 계산결과 어떻게 나오는건지 모르겠습니다. ((50+1)*3 = 155바이트??)

**Comment by KS-KIM** [comment]
https://github.com/7ieon/SQLtune/blob/main/chapter3.sql

**Comment by KS-KIM** [comment]
group by절 없이 max 사용하는것 차이 찾아보기

**Comment by ksy90101** [comment]
https://medium.com/watcha/%EC%BF%BC%EB%A6%AC-%EC%B5%9C%EC%A0%81%ED%99%94-%EC%B2%AB%EA%B1%B8%EC%9D%8C-%EB%B3%B4%EB%8B%A4-%EB%B9%A0%EB%A5%B8-%EC%BF%BC%EB%A6%AC%EB%A5%BC-%EC%9C%84%ED%95%9C-7%EA%B0%80%EC%A7%80-%EC%B2%B4%ED%81%AC-%EB%A6%AC%EC%8A%A4%ED%8A%B8-bafec9d2c073

**Comment by KS-KIM** [comment]
https://wbluke.tistory.com/27

**Comment by KS-KIM** [comment]
https://www.jetbrains.com/help/datagrip/creating-diagrams.html
