### ISSUE TITLE
CHAPTER 2 아키텍처 개요

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#2]
질문을 남겨주세요!

**Comment by ksy90101** [comment]
1. 서비스가 도메인으로 여기서 소개 되고 있는건가요,,,!? 서비스의 존재가 어디인지 잘 모르겠네요 ㅠㅠ

**Comment by ksy90101** [comment]
잘못된 DIP 적용 예가 잘 이해가 가지 않네요.
도메인 영역이 구현 기술을 다루는 인프라스트럭처 영역에 의존하고 있다는말이 잘 모르겟습니다 ㅠㅠ

**Comment by dreamary-kskim** [comment]
DIP를 적용하기 위해 고수준 모듈에서 인터페이스를 정의한 후, 구현체인 저수준 모듈을 개발합니다.
추후에 구현 기술을 변경할 때, 기존 인터페이스의 설계적인 결함이 발견되어 변경이 불가피하다면 어떻게 대처할 수 있을까요?
해당 인터페이스를 의존하고 있는 모든 고수준 모듈은 변경이 불가피하겠죠...?

**Comment by dreamary-kskim** [comment]
> 서비스가 도메인으로 여기서 소개 되고 있는건가요,,,!? 서비스의 존재가 어디인지 잘 모르겠네요 ㅠㅠ

서비스는 응용 계층으로 소개가 되어 있습니다. 책 내의 예시에서 `CalculateDiscountService`를 도메인 패키지에 두고 있는 것 때문에 헷갈릴 수 있다고 보는데, `CalculateDiscountService`는 도메인의 비즈니스를 담고 있는 '도메인 서비스'로 보는게 맞을 것 같습니다. 위 책의 7장에서 다루게 될 내용이므로 간단히만 언급하자면, 우리가 일반적으로 생각하는 어플리케이션 계층의 서비스는 '어플리케이션 서비스'이고, 비즈니스 로직을 담고있는 도메인 계층에 속하는 서비스는 '도메인 서비스'라고 보시면 될 것 같습니다.

---

> 잘못된 DIP 적용 예가 잘 이해가 가지 않네요.
도메인 영역이 구현 기술을 다루는 인프라스트럭처 영역에 의존하고 있다는말이 잘 모르겟습니다 ㅠㅠ

![image](https://user-images.githubusercontent.com/83330495/121785828-0ff4e380-cbf7-11eb-9ec1-9a17c4b3cc44.png)

이 이미지를 보시면 DIP를 적용하기 위해 할인 규칙을 계산하는 규칙 엔진을 추상화한 `RuleDiscounter` 인터페이스를 생성했습니다. 그리고 `CalculateDiscountService`는 해당 인터페이스를 바라봄으로써 구현 기술의 내용을 담고있는 `DroolsRuleDiscounter`에 직접 의존하지 않습니다. 하지만, `RuleDiscounter` 인터페이스는 인프라스트럭처 패키지에 있기 때문에 저수준 관점에서 추상화를 한 것입니다.

`RuleDiscounter`를 저수준 관점에서 추상화 했다는 말이 와닿지 않을 수 있으니, 간단한 예시를 통해 부연 설명을 하겠습니다.
42p의 `DroolsRuleEngine` 클래스를 보면 `evalute`라는 함수가 보이죠? 이 클래스만 보고 단순히 인터페이스를 다음과 같이 추출한다고 생각해 보겠습니다.

```java
public interface DiscountRule {
  public void applyRule(String sessionName, Customer customer, List<OrderLine> orderLines);
}
```

책에서 언급되었다시피(43p), `sessionName`은 Drools의 세션 이름을 의미하므로 위 인터페이스는 저수준의 관점에서 추상화를 했다고 볼 수 있습니다. 결국 기술에 의존적인 구조가 되는 것이고, 다른 규칙 엔진으로 변경된다면 무효한 추상화가 됩니다. 고수준의 관점에서 추상화를 했다면 `sessionName`이 인터페이스의 인자로 추출될 일이 없었겠죠?

![image](https://user-images.githubusercontent.com/83330495/121785833-1a16e200-cbf7-11eb-8abd-09ce3aa29999.png)

고수준인 도메인 계층 관점에서 RuleDiscounter를 추상화한 결과는 위 이미지와 같습니다. `sessionName`과 같은 저수준에 의존적인 내용이 하나도 담겨있지 않겠죠? 변경에 좀 더 유연해졌겠네요.

이쪽 예시를 보니 제가 남긴 질문과도 연계가 되네요. 인터페이스의 설계적인 결함을 피하기 위해서는 저수준의 관점이 아닌, 고수준의 관점에서 추상화를 해야한다는 이야기가 되겠네요.

**Comment by dreamary-kskim** [comment]
우리가 일반적으로 개발할 때, Repository는 인터페이스로 생성하되 JpaRepository를 상속하는 인터페이스를 생성합니다. JpaRepository는 JPA라는 구현체에 의존적인 형태이기 때문에 엄격하게 레이어를 구분하기 위해서는 순수한 Repository 인터페이스를 추출하여 domain 패키지로 분류하고, 이를 구현하는 JpaRepository를 infrastructure 패키지로 분류해야 한다고 생각하는데, 다른 분들의 의견은 어떤지 알고 싶습니다. 또한, 현업에서 Java를 쓰는 경우에는 어떻게 되어있는지도 궁금합니다.

**Comment by KS-KIM** [comment]
Q)

DIP를 적용하기 위해 고수준 모듈에서 인터페이스를 정의한 후, 구현체인 저수준 모듈을 개발합니다.

추후에 구현 기술을 변경할 때, 기존 인터페이스의 설계적인 결함이 발견되어 변경이 불가피하다면 어떻게 대처할 수 있을까요?

해당 인터페이스를 의존하고 있는 모든 고수준 모듈은 변경이 불가피하겠죠...?

**Comment by KS-KIM** [comment]
Q)

우리가 일반적으로 개발할 때, Repository는 인터페이스로 생성하되 JpaRepository를 상속하는 인터페이스를 생성합니다. JpaRepository는 JPA라는 구현체에 의존적인 형태이기 때문에 엄격하게 레이어를 구분하기 위해서는 순수한 Repository 인터페이스를 추출하여 domain 패키지로 분류하고, 이를 구현하는 JpaRepository를 infrastructure 패키지로 분류해야 한다고 생각하는데, 다른 분들의 의견은 어떤지 알고 싶습니다. 또한, 현업에서 Java를 쓰는 경우에는 어떻게 되어있는지도 궁금합니다.

자문자답) 이전에 최범균님 유튜브 영상에서 언급되었던 내용이네요. [참고 링크](https://youtu.be/MMH_ht8pf8U)

**Comment by KS-KIM** [comment]
## Q1)

> 서비스가 도메인으로 여기서 소개 되고 있는건가요,,,!? 서비스의 존재가 어디인지 잘 모르겠네요 ㅠㅠ

## A1)

서비스는 응용 계층으로 소개가 되어 있습니다. 책 내의 예시에서 `CalculateDiscountService`를 도메인 패키지에 두고 있는 것 때문에 헷갈릴 수 있다고 보는데, `CalculateDiscountService`는 도메인의 비즈니스를 담고 있는 '도메인 서비스'로 보는게 맞을 것 같습니다. 위 책의 7장에서 다루게 될 내용이므로 간단히만 언급하자면, 우리가 일반적으로 생각하는 어플리케이션 계층의 서비스는 '어플리케이션 서비스'이고, 비즈니스 로직을 담고있는 도메인 계층에 속하는 서비스는 '도메인 서비스'라고 보시면 될 것 같습니다.

## Q2)

> 잘못된 DIP 적용 예가 잘 이해가 가지 않네요.
도메인 영역이 구현 기술을 다루는 인프라스트럭처 영역에 의존하고 있다는말이 잘 모르겟습니다 ㅠㅠ

## A2)

![https://user-images.githubusercontent.com/83330495/121785828-0ff4e380-cbf7-11eb-9ec1-9a17c4b3cc44.png](https://user-images.githubusercontent.com/83330495/121785828-0ff4e380-cbf7-11eb-9ec1-9a17c4b3cc44.png)

이 이미지를 보시면 DIP를 적용하기 위해 할인 규칙을 계산하는 규칙 엔진을 추상화한 `RuleDiscounter` 인터페이스를 생성했습니다. 그리고 `CalculateDiscountService`는 해당 인터페이스를 바라봄으로써 구현 기술의 내용을 담고있는 `DroolsRuleDiscounter`에 직접 의존하지 않습니다. 하지만, `RuleDiscounter` 인터페이스는 인프라스트럭처 패키지에 있기 때문에 저수준 관점에서 추상화를 한 것입니다.

`RuleDiscounter`를 저수준 관점에서 추상화 했다는 말이 와닿지 않을 수 있으니, 간단한 예시를 통해 부연 설명을 하겠습니다. (다소 억지스러운 예시일 수도 있습니다.)

42p의 `DroolsRuleEngine` 클래스를 보면 `evalute`라는 함수가 보이죠? 이 클래스만 보고 단순히 인터페이스를 다음과 같이 추출한다고 생각해 보겠습니다.

```java
public interface DiscountRule {
  public void applyRule(String sessionName, Customer customer, List<OrderLine> orderLines);
}

```

책에서 언급되었다시피(43p), `sessionName`은 Drools의 세션 이름을 의미하므로 위 인터페이스는 저수준 관점에서 추상화를 했다고 볼 수 있습니다. 결국 기술에 의존적인 구조가 되는 것이고, 다른 규칙 엔진으로 변경된다면 무효한 추상화가 됩니다. 고수준 관점에서 추상화를 했다면 저수준 모듈의 의존성을 가지는 `sessionName`이 인터페이스의 인자로 추출될 일이 없었겠죠?

![https://user-images.githubusercontent.com/83330495/121785833-1a16e200-cbf7-11eb-8abd-09ce3aa29999.png](https://user-images.githubusercontent.com/83330495/121785833-1a16e200-cbf7-11eb-8abd-09ce3aa29999.png)

고수준인 도메인 계층 관점에서 RuleDiscounter를 추상화한 결과는 위 이미지와 같습니다. `sessionName`과 같은 저수준에 의존적인 내용이 하나도 담겨있지 않겠죠? 변경에 좀 더 유연해졌겠네요.

이쪽 예시를 보니 제가 남긴 질문과도 연계가 되네요. 인터페이스의 설계적인 결함을 피하기 위해서는 저수준의 관점이 아닌, 고수준의 관점에서 추상화를 해야한다는 이야기가 되겠네요.

**Comment by KS-KIM** [comment]
[안정된 의존관계 원칙과 안정된 추상화 원칙에 대하여 - 우아한형제들 기술 블로그](https://woowabros.github.io/study/2018/03/05/sdp-sap.html)

**Comment by aegis1920** [comment]
> Q)
> DIP를 적용하기 위해 고수준 모듈에서 인터페이스를 정의한 후, 구현체인 저수준 모듈을 개발합니다.
> 추후에 구현 기술을 변경할 때, 기존 인터페이스의 설계적인 결함이 발견되어 변경이 불가피하다면 어떻게 대처할 수 있을까요?
> 해당 인터페이스를 의존하고 있는 모든 고수준 모듈은 변경이 불가피하겠죠...?

기존 인터페이스의 설계적인 결함이 발견되어도 하위 호환성을 위해 어쩔 수 없이 같이 가져가야함. (이것이 바로 레거시ㅠ)

다음부터는 여기에 답변 먼저 적도록 하겠습니다. 🙇‍♂️

**Comment by KS-KIM** [comment]
부득이한 경우 어댑터를 사용할 수도 있을 것 같아요. 단, 무분별한 어댑터의 남용은 또 다른 스파게티 코드를 야기할 수 있을 것 같네요😢
