### ISSUE TITLE
CHAPTER 4 악성 SQL 튜닝으로 초보자 탈출하기

### ISSUE THREAD

**Issue by ksy90101** [Woohan-TDD/ddd-start#20]

**Comment by KS-KIM** [comment]
208p 두번째 튜닝 후 책가 다른 결과 도출됨 (filtered 항목이 50.00으로 나와있으나 실제 수행시 33.33)

**Comment by ksy90101** [comment]
p213 튜닝 전 쿼리의 실행계획이 아예 다르게 나옴

**Comment by KS-KIM** [comment]
228p 사원.사원번호 > 450000절이 급여.사원번호 > 450000으로 변형되어 적용되는지? 오히려 돌려봤을 때 반대로임.(급여로 설정하면 사원으로 바뀜)

**Comment by aegis1920** [comment]
https://engineering.linecorp.com/ko/blog/mysql-workbench-visual-explain-index/

**Comment by KS-KIM** [comment]
http://wiki.gurubee.net/pages/viewpage.action?pageId=26741725
