### ISSUE TITLE
CHAPTER 5 악성 SQL 튜닝으로 전문가 되기

### ISSUE THREAD

**Issue by ksy90101** [Woohan-TDD/ddd-start#21]

**Comment by KS-KIM** [comment]
- [index skip scan 설명](https://myjamong.tistory.com/237)
- [index skip scan 활용 사례](https://jojoldu.tistory.com/172)

multi column index에서 후행 인덱스만 조건절에서 사용할 때 발생한다.
선행 조건은 필터링이 불가능하여 무조건 접근해야 하지만, 후행 조건에서는 인덱스를 통해 스킵할 수 있는 경우 적용 가능하다.
선행 조건의 카디널리티가 낮을 때 사용하면 효과적이다.
-> 선행 조건의 카디널리티가 낮으면 후행 조건이 인덱스 선두에 와야하지 않았을까 싶긴 하다. 하지만 프로덕션 환경에서는 마음대로 인덱스를 바꾸기 어려울 수 있으므로 skip scan 힌트를 활용할 수 있을 것이다.

**Comment by KS-KIM** [comment]
| 콜레이션 | 알파벳 대소문자 구분 | 전각/반각 문자 구분 | 이모지 문자 구분 | 
|---|---|---|---|
| utf8mb4_general_ci | X | O | X |
| utf8mb4_bin | O | O | O |
| utf8mb4_unicode_ci | X | X | X |

- 콜레이션: 정렬 방식의 차이. 성능 vs 정확도
- utf8mb4는 모두 가변 4바이트 문자열이다. 이모지는 모두 4바이트 문자열로 표현된다.

- [참고](https://sshkim.tistory.com/128)

**Comment by KS-KIM** [comment]
- [콜레이션 비교](https://www.dante2k.com/530)
- [utf8_general_ci와 utf8_unicode_ci 비교-1](https://haloes.tistory.com/219)
- [utf8_general_ci와 utf8_unicode_ci 비교-2](https://forums.mysql.com/read.php?103,187048,188748#msg-188748)

### utf8_general_ci
- 성능을 우선시한다.
- 정렬시 빠른 속도를 보인다.
- 악센트 문자가 없어서 치환된다. (e.g. ÀÁÅåāă -> AAAaaa)

### utf8_unicode_ci
- 성능보다는 정확도를 우선시한다. 
- 악센트 문자를 식별 가능하다. (e.g. ÀÁÅåāă)
