### ISSUE TITLE
CHAPTER 3 애그리거트

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#3]
질문을 남겨주세요!

**Comment by ksy90101** [comment]
https://present.do/decks/60bed187f79479437375f362?page=9

**Comment by ksy90101** [comment]
객체참조보다 ID 참조를 하라고 적혀 있는데, ID 참조 하실까요?

**Comment by KS-KIM** [comment]
마지막 팩토리 메서드 예시에서, product를 store에서 생성하도록 구현하면 store가 product에 대한 의존이 생기고, product 생성 방식에 변경이 발생하면 변경의 여파가 store에까지 퍼지게 되는 것 아닌가요...?

**Comment by KS-KIM** [comment]
> 어떤 예약의 매장의 연락처를 알고 싶으면 reservation.getShop().getContactPhoneNumber() 로 접근하면 됩니다.

자주 참고했던 DDD 관련 자료(https://brunch.co.kr/@cg4jins/7) 에서 조회의 목적으로 사용했던 객체 참조가 자칫 잘못하면 애그리거트 간 의존으로 인해 확장하기 어려운 형태가 될 수도 있겠네요. (e.g. 각 애그리거트를 서로 다른 서비스에서 제공하는 경우)

그래서 본문에 Aggregate를 적용하지는 않았다고 나와있네요.

> 모델 객체를 생성할 때 Factory를 사용했습니다. Aggregate를 적용하지 못한 것은 그 구현이 쉽지 않았기 때문입니다. 그리고 JPA의 Lazy loading를 사용하니 딱히 Aggregate가 필요하진 않았습니다.

서비스 규모나 개발 환경에 따라 적절하게 선택하면 될 것 같아요.

**Comment by ksy90101** [comment]
https://github.com/ChristophKnabe/spring-ddd-bank

**Comment by ksy90101** [comment]
https://www.baeldung.com/spring-entityscan-vs-componentscan

**Comment by ksy90101** [comment]
https://www.infoq.com/news/2008/02/ddd-di-aop/
