### ISSUE TITLE
CHAPTER 4 리포지터리와 모델구현(JPA 중심)

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#4]
질문을 남겨주세요!

**Comment by KS-KIM** [comment]
133p. 상속 말고 ImageType을 enum으로 만들어 전략패턴 적용하면 되지 않을까 싶습니다.

**Comment by aegis1920** [comment]
@KS-KIM 저도 이미지 타입이라면 그게 더 나은 방법이라고 생각합니다. 책에서는 밸류 타입의 상속구조를 설명하고 싶은데 예시로 마땅한 게 없어 이미지 타입 예시를 들었다고 감히 예측해봅니다 :)

**Comment by ksy90101** [comment]
저도 동의합니다. 
사실 예제가 없어서 그렇지 않을까 합니다 ㅎㅎ

**Comment by ksy90101** [comment]
JPA 연관관계에서 List vs Set의 차이가 무엇일까요?

참고링크
(https://stackoverflow.com/questions/13101882/jpa-onetomany-list-vs-set)
https://dzone.com/articles/why-set-is-better-than-list-in-manytomany

```
하나는 일대다 필드의 타입을 Set으로 선언하는 것입니다.
(Set은 중복을 허용하지 않는 자료구조이기 때문에 중복등록이 되지 않습니다.)

    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name="academy_id")
    private Set<Subject> subjects = new LinkedHashSet<>();
(Set이 순서가 보장되지 않기에 LinkedHashSet을 사용하여 순서를 보장합니다.)

2번째 방법은 distinct를 사용하여 중복을 제거하는 것입니다.
(Set보다는 List가 더 적합하다고 판단되신다면)
```
