### ISSUE TITLE
CHAPTER 6 응용 서비스와 표현 영역

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#6]
질문을 남겨주세요!

**Comment by ksy90101** [comment]
p180 응용 서비스의 인터페이스와 클래스에서 말하고자 하는 바를 이해하지 못하겠습니다.
인터페이스를 모두 만드는게 좋다는 건지, 아니면 적당히 만들라는건지, 결론을 찾기가 조금 힘드네요.

**Comment by ksy90101** [comment]
값 검증을 할때 응용 서비스나 표현 영역에서 하라고 하는데 저는 DTO가 맞다고 생각하는데 어떻게 생각하시나요?

**Comment by ksy90101** [comment]
조회 전용이면 표현 영역에서 구현해도 된다고 하는데 어떻게 생각하시나요?

**Comment by aegis1920** [comment]
위에 대한 답변입니다.

> p180 응용 서비스의 인터페이스와 클래스에서 말하고자 하는 바를 이해하지 못하겠습니다.
> 인터페이스를 모두 만드는게 좋다는 건지, 아니면 적당히 만들라는건지, 결론을 찾기가 조금 힘드네요.

p181에 나와있는 내용을 간단히 정리해보겠습니다. 

응용 서비스를 구현할 때 인터페이스를 사용한다면

1. 소스 파일이 많아진다
2. 구현 클래스에 대한 간접 참조가 증가해서 전체 구조만 복잡해지는 문제가 발생한다

그리고

1. 단위테스트 시, Mockito를 이용해 클래스에 대해서도 가짜 객체를 만들 수 있어 **인터페이스가 없어도** 테스트할 수 있다

결국

1. 인터페이스를 구현하는 클래스가 다수 존재하는 경우
2. 런타임에 구현 객체를 교체하는 경우
3. TDD와 같이 역할(인터페이스)을 먼저 정의해야하는 경우

가 아닌 이상, 응용 서비스에 대해서 인터페이스를 만드는 건 좋은 설계가 아니라고 이야기하고 있습니다. 저 또한 같은 의견이구요 :)


> 값 검증을 할때 응용 서비스나 표현 영역에서 하라고 하는데 저는 DTO가 맞다고 생각하는데 어떻게 생각하시나요?

제 생각은 조금 다른데요. 값 검증을 DTO에서 하는 건 DTO의 역할과 맞지 않다고 생각합니다. DTO는 말 그대로 데이터를 전송하는 객체로 데이터를 전송하는 역할을 해야합니다. (사실, 이렇게 이야기를 해도 지켜지지 않는 게 현실이죠ㅎㅎ)

제가 오히려 질문드리고 싶은 점도 있는데요. 요청 값에 대한 검증, 논리적 오류 모두 DTO에서 해야된다는 의미로 질문주신 걸까요?

> 조회 전용이면 표현 영역에서 구현해도 된다고 하는데 어떻게 생각하시나요?

저는 책의 생각과 같습니다. 트랜잭션도 없는 조회 전용일 경우, 서비스 레이어를 만들 이유가 없습니다. 굳이 서비스 레이어를 만들 이유가 없다면 표현 영역에서 구현해도 괜찮지 않을까요? 소스 파일도 줄고 소스 코드 안으로 한 번 더 안 들어가도 되니 가독성이 증가하는 이점도 얻을 수 있을 것 같습니다.

**Comment by aegis1920** [comment]
p.192에 changePassword() 의 인자를 보면 ChangePasswordRequest가 있습니다.

인자에 @RequestBody를 붙인 경우, ArgumentResolver를 거치고 Jackson2를 거쳐서 ObjectMapper를 통해 매핑되는 것으로 알고있는데요.
이렇게 @RequestBody가 없는 경우는 어떻게 동작하는지 궁금하네요 :)

**Comment by KS-KIM** [comment]
p179 각 기능을 클래스로 쪼개서 구현하는 경우, 공통 기능을 구현할 때 헬퍼 클래스를 사용하고 싶지 않다면 빈 주입을 받을 수 있는 공통 서비스 클래스를 만드는게 나을까요? 이렇게 구현하면 같은 서비스지만 양방향 의존을 조심해야 해서 다소 불편함이 있을 것 같기도 한데, 책 예시보다는 유연할 것 같습니다.

**Comment by KS-KIM** [comment]
> p180 응용 서비스의 인터페이스와 클래스에서 말하고자 하는 바를 이해하지 못하겠습니다. 인터페이스를 모두 만드는게 좋다는 건지, 아니면 적당히 만들라는건지, 결론을 찾기가 조금 힘드네요.

예전에도 인용했던 글인데, 잘 정리되어 있어 공유합니다. 

---
**인프라성 서비스와 Repository**

Email 발송, Push, SMS 발송, Logging 등등 인프라성 코드는 거의 불안정성이 0에 가깝습니다(안정적). 호출자는 매우 많은데 그 자신이 의존하는 것은 별로 많지 않은 경우가 많습니다. 그러면서도 그 구현체는 시스템의 성장에 따라 바뀌기 쉽습니다(Email의 경우 SMTP → DB → MQ). 안정성이 높으면 변경 대응을 위해 추상적이어야 합니다.

따라서 인프라성 Service는 거의 무조건 interface를 구현해야 하며, 위에서 제가 말한 추상성의 의미 – 인터페이스의 메소드 시그너처에 구현에 구현의 상세를 포함하지 말 것 -을 지켜야 합니다.

...생략

**비즈니스 서비스**

비즈니스 로직 서비스는 상황을 지켜봐야 할 것으로 생각됩니다. 처음부터 무작정 인터페이스를 만들면 복잡도만 높고 개발 효율은 떨어질 수 있습니다(쓸모없는 지역).

비즈니스의 성장에 따라 고통스러운 순간이 오거나 혹은 측정에 의해 인터페이스로 분리하는 작업을 해도 될 것 같습니다.

[안정된 의존관계 원칙과 안정된 추상화 원칙에 대하여 | 우아한형제들 기술블로그](https://techblog.woowahan.com/2561/)

---

TDD는 하고싶고, 서비스의 인터페이스는 불필요해 보이고, mocking 라이브러리는 사용하기 싫다면 일단 서비스 구현체에서 가짜 응답을 임의로 내리게 만들어 테스트를 통과한 뒤에 구현체를 만들어 테스트를 통과시키는 식으로 개발할 수도 있을 것 같아요. 단, 이렇게 구현하면 표현 영역을 테스트 할 때 서비스 구현체를 의존해야겠네요. 

> 값 검증을 할때 응용 서비스나 표현 영역에서 하라고 하는데 저는 DTO가 맞다고 생각하는데 어떻게 생각하시나요?

책에서는 값 검증의 대상을 크게 두가지로 나누고 있습니다.

1. 단순 값의 유효성 검증 (e.g. 숫자의 범위, 문자열 길이 등)
2. 논리적 검증 (e.g. 아이디가 유일한지)

Spring Validation을 이용하여 DTO 검증을 수행하는 것은 표현 영역에서 값 검증을 하는것으로 봐야할 것 같습니다.
아이디 유일성 검사와 같은 경우에는 리파지토리를 거쳐서 해당 아이디가 있는지 검사하기 때문에 응용 서비스의 값 검증으로 보는게 맞는 것 같습니다.

이와 별개로, 비즈니스적인 의미를 가지는 유효성 검사가 필요한 경우 표현 영역이 아닌 도메인 영역에서 검증을 수행해야 할 것 같습니다. (도메인 생성자에서 검증)

> 인자에 @requestbody를 붙인 경우, ArgumentResolver를 거치고 Jackson2를 거쳐서 ObjectMapper를 통해 매핑되는 것으로 알고있는데요. 이렇게 @requestbody가 없는 경우는 어떻게 동작하는지 궁금하네요 :)

이전 제 경험에 의하면 동작하지 않을 것 같습니다. ddd-start 예제 코드 repository 가보면 @ModelAttribute로 요청 form body 매핑해둔걸 보니 책에서 빠트린거 아닌가 싶네요.

**Comment by KS-KIM** [comment]
참고: [잊을만 하면 돌아오는 정산 신병들 | 우아한형제들 기술블로그](https://techblog.woowahan.com/2711/)

**Comment by KS-KIM** [comment]
참고: [DTO](https://www.youtube.com/watch?v=MIYwej-VodE&feature=youtu.be)

**Comment by ksy90101** [comment]
[레디스 트랜잭션]
https://docs.spring.io/spring-data/redis/docs/2.5.2/reference/html/#tx.spring

**Comment by aegis1920** [comment]
https://www.youtube.com/watch?v=MIYwej-VodE

**Comment by KS-KIM** [comment]
참고: [redis transaction](https://docs.spring.io/spring-data/redis/docs/2.5.2/reference/html/#tx.spring)
