### ISSUE TITLE
CHAPTER 8 애그리거트 트랜잭션 관리

### ISSUE THREAD

**Issue by aegis1920** [Woohan-TDD/ddd-start#8]
질문을 남겨주세요!

**Comment by aegis1920** [comment]
p227에서 "JPA는 이런 문제를 처리할 수 있도록 EntityManager#find() 메서드로 엔티티를 구할 때 강제로 버전 값을 증가시키는 잠금 모드를 지원하고 있다"고 합니다. 그런데 이렇게 하면 find를 하고 해당 엔티티를 변경하지 않더라도 버전이 증가해버리지 않나요? 본인이 해당 엔티티에서 변경이 일어날 지 파악하고 써야되는 건지 궁금하네요!

**Comment by ksy90101** [comment]
`OPTIMISTIC_FORCEJNCREMENT` 이거 자체가 수정하지 않아도 조회하는 순간 강제로 올리는 것이라고 설명하고 있네요.
여기서도 애그리거트 루트가 변경되지 않았지만 가지고 있는 엔티티가 변경되었을때를 말하기 때문에 버전이 증가되는 것이 맞다고 생각하네요.
저 옵션 자체는 조회를 하는 순간 버전을 올리는 것에 목표를 하고 있는거 같아요.
말씀하신 대로 해당 엔티티에서 변경이 일어날지 파악하고 써야 한다면, 자체 구현을 할수 잇을거 같다는 생각이 드네요.

**Comment by ksy90101** [comment]
https://www.baeldung.com/cs/offline-concurrency-control
